version: '3.8'

services:
  sqlpreview:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    container_name: sqlpreview
    hostname: sqlpreview
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "yourStrong(!)Password"
      MSSQL_PID: "Evaluation"
    ports:
      - "1433:1433"
    networks:
      - my-network
  
  reservesystem:
    image: reservesystem
    container_name: reservesystem
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge